on: 
  release:
    types:
      - created
    branches:
      - main
  workflow_dispatch:
    
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Install npm dependencies
        run: npm install
      - name: Run lint task
        run: npm run lint --if-present
      - name: Run build task
        run: npm run build --if-present
      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
